<a href="https://colab.research.google.com/github/patilr4046-star/For-ML-work/blob/main/ai_student_impact_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [3]:
from google.colab import files
uploaded = files.upload()

Saving ai_student_impact_dataset (1).csv to ai_student_impact_dataset (1).csv

In [4]:
df = pd.read_csv('ai_student_impact_dataset (1).csv')

In [5]:
df

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
49996,149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
49997,149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
49998,149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
49999,150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low

In [6]:
df.shape

(50000, 16)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  50000 non-null  int64
 1   Major_Category              50000 non-null  object
 2   Year_of_Study               50000 non-null  object
 3   Pre_Semester_GPA            50000 non-null  float64
 4   Weekly_GenAI_Hours          50000 non-null  float64
 5   Primary_Use_Case            50000 non-null  object
 6   Prompt_Engineering_Skill    50000 non-null  object
 7   Tool_Diversity              50000 non-null  int64
 8   Paid_Subscription           50000 non-null  bool
 9   Traditional_Study_Hours     50000 non-null  float64
 10  Perceived_AI_Dependency     50000 non-null  int64
 11  Institutional_Policy        50000 non-null  object
 12  Anxiety_Level_During_Exams  50000 non-null  int64
 13  Post_Semester_GPA           50000 non-null  float64
 14  Skill_Retention_Score       50000 non-null  float64
 15  Burnout_Risk_Level          50000 non-null  object
dtypes: bool(1), float64(5), int64(4), object(6)
memory usage: 5.8+ MB

In [8]:
df.describe()

,Student_ID,Pre_Semester_GPA,Weekly_GenAI_Hours,Tool_Diversity,Traditional_Study_Hours,Perceived_AI_Dependency,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score
count,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,125000.500000,3.146102,8.427752,2.80026,11.209271,3.505360,4.270760,3.349299,75.798125
std,14433.901067,0.478854,8.269490,1.18802,5.156426,1.820812,2.144066,0.495673,13.281626
min,100001.000000,1.183000,0.000000,1.00000,1.000000,1.000000,1.000000,1.000000,10.780000
25%,112500.750000,2.834000,2.390000,2.00000,7.560000,2.000000,3.000000,3.023750,66.820000
50%,125000.500000,3.210000,5.800000,3.00000,11.180000,3.000000,4.000000,3.421000,76.000000
75%,137500.250000,3.521000,11.720000,4.00000,14.710000,5.000000,6.000000,3.749000,85.190000
max,150000.000000,3.998000,40.000000,5.00000,35.860000,10.000000,10.000000,4.000000,100.000000

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
X = df.drop(['Anxiety_Level_During_Exams', 'Burnout_Risk_Level', 'Institutional_Policy',], axis=1, inplace = True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Student_ID                50000 non-null  int64
 1   Major_Category            50000 non-null  object
 2   Year_of_Study             50000 non-null  object
 3   Pre_Semester_GPA          50000 non-null  float64
 4   Weekly_GenAI_Hours        50000 non-null  float64
 5   Primary_Use_Case          50000 non-null  object
 6   Prompt_Engineering_Skill  50000 non-null  object
 7   Tool_Diversity            50000 non-null  int64
 8   Paid_Subscription         50000 non-null  bool
 9   Traditional_Study_Hours   50000 non-null  float64
 10  Perceived_AI_Dependency   50000 non-null  int64
 11  Post_Semester_GPA         50000 non-null  float64
 12  Skill_Retention_Score     50000 non-null  float64
dtypes: bool(1), float64(5), int64(3), object(4)
memory usage: 4.6+ MB

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [13]:
df.head()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Post_Semester_GPA,Skill_Retention_Score
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,2.393,86.44
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,3.696,69.39
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,3.499,73.93
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,4.000,63.58
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,3.798,100.00

In [14]:
df["Major_Category"] = le.fit_transform(df["Major_Category"])
df["Year_of_Study"] = le.fit_transform(df["Year_of_Study"])
df["Primary_Use_Case"] = le.fit_transform(df["Primary_Use_Case"])
df["Prompt_Engineering_Skill"] = le.fit_transform(df["Prompt_Engineering_Skill"])

In [15]:
df = df.astype(int)

In [16]:
df.head()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Post_Semester_GPA,Skill_Retention_Score
0,100001,2,3,2,23,0,1,1,1,8,5,2,86
1,100002,3,2,3,1,3,0,5,0,16,3,3,69
2,100003,1,0,3,21,4,1,2,0,10,5,3,73
3,100004,1,3,3,1,0,2,4,0,15,2,4,63
4,100005,4,4,3,9,1,0,4,0,12,4,3,100

In [17]:
X = df.drop("Post_Semester_GPA", axis = 1)
y = df["Post_Semester_GPA"]

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [19]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(X_train, y_train)

LogisticRegression()

In [20]:
y_pred = model.predict(X_test)

In [21]:
y_pred

array([3, 3, 3, ..., 3, 3, 3])

In [22]:
y_test

33553    2
9427     3
199      3
12447    2
39489    3
        ..
27615    2
21964    1
33321    3
40225    3
28203    3
Name: Post_Semester_GPA, Length: 16500, dtype: int64

In [23]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report

In [24]:
accuracy_score(y_test, y_pred)

0.6657575757575758

In [25]:
confusion_matrix(y_test, y_pred)

array([[    0,     0,   151,     0],
       [    3,     0,  3767,     0],
       [    0,     0, 10985,     1],
       [    0,     0,  1593,     0]])

In [26]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00       151
           2       0.00      0.00      0.00      3770
           3       0.67      1.00      0.80     10986
           4       0.00      0.00      0.00      1593

    accuracy                           0.67     16500
   macro avg       0.17      0.25      0.20     16500
weighted avg       0.44      0.67      0.53     16500

In [27]:
df

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Post_Semester_GPA,Skill_Retention_Score
0,100001,2,3,2,23,0,1,1,1,8,5,2,86
1,100002,3,2,3,1,3,0,5,0,16,3,3,69
2,100003,1,0,3,21,4,1,2,0,10,5,3,73
3,100004,1,3,3,1,0,2,4,0,15,2,4,63
4,100005,4,4,3,9,1,0,4,0,12,4,3,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,149996,1,3,2,12,0,1,2,0,13,2,3,66
49996,149997,4,3,2,2,0,2,1,0,4,3,3,81
49997,149998,1,3,3,15,4,0,5,1,3,4,3,97
49998,149999,1,2,3,19,1,2,5,0,7,5,3,84
49999,150000,0,4,3,3,0,1,1,0,3,2,3,76

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [29]:
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.fit_transform(X_test)

In [30]:
from sklearn.neighbors import KNeighborsClassifier

In [31]:
knn_model = KNeighborsClassifier(n_neighbors = 5)

In [32]:
knn_model.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [33]:
y_pred_knn = knn_model.predict(X_test_scaled)

In [34]:
accuracy_score(y_test, y_pred_knn)

0.7406666666666667

In [35]:
confusion_matrix(y_test, y_pred_knn)

array([[  40,  105,    6,    0],
       [  40, 2735,  995,    0],
       [   1, 1346, 9331,  308],
       [   0,    1, 1477,  115]])

In [36]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00       151
           2       0.00      0.00      0.00      3770
           3       0.67      1.00      0.80     10986
           4       0.00      0.00      0.00      1593

    accuracy                           0.67     16500
   macro avg       0.17      0.25      0.20     16500
weighted avg       0.44      0.67      0.53     16500

In [37]:
from sklearn.naive_bayes import GaussianNB

In [38]:
model_NB = GaussianNB()

In [39]:
model_NB.fit(X_train, y_train)

GaussianNB()

In [40]:
y_pred_NB = model_NB.predict(X_test)

In [41]:
y_pred_NB

array([2, 3, 3, ..., 3, 3, 3])

In [42]:
accuracy_score(y_test, y_pred_NB)

0.7319393939393939

In [43]:
from sklearn.tree import DecisionTreeClassifier

In [44]:
model_DT = DecisionTreeClassifier(random_state= 42)

In [45]:
model_DT.fit(X_train_scaled, y_train)

DecisionTreeClassifier(random_state=42)

In [46]:
y_pred_DT = model_DT.predict(X_test_scaled)

In [47]:
y_pred_DT

array([2, 2, 3, ..., 3, 3, 3])

In [48]:
accuracy_score(y_test, y_pred_DT)

0.6688484848484848

In [49]:
from sklearn.svm import SVC

In [50]:
model_svm = SVC(kernel = 'linear')

In [51]:
model_svm.fit(X_train_scaled, y_train)

SVC(kernel='linear')

In [52]:
y_pred_svc = model_svm.predict(X_test_scaled)

In [53]:
accuracy_score(y_test, y_pred_svc)

0.7623636363636364

In [54]:
df

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Post_Semester_GPA,Skill_Retention_Score
0,100001,2,3,2,23,0,1,1,1,8,5,2,86
1,100002,3,2,3,1,3,0,5,0,16,3,3,69
2,100003,1,0,3,21,4,1,2,0,10,5,3,73
3,100004,1,3,3,1,0,2,4,0,15,2,4,63
4,100005,4,4,3,9,1,0,4,0,12,4,3,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,149996,1,3,2,12,0,1,2,0,13,2,3,66
49996,149997,4,3,2,2,0,2,1,0,4,3,3,81
49997,149998,1,3,3,15,4,0,5,1,3,4,3,97
49998,149999,1,2,3,19,1,2,5,0,7,5,3,84
49999,150000,0,4,3,3,0,1,1,0,3,2,3,76

In [55]:
X = df.drop("Post_Semester_GPA", axis = 1)
y = df["Post_Semester_GPA"]

In [56]:
from sklearn.model_selection import cross_val_score

In [60]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [58]:
scores = cross_val_score(model_svm, X_scaled,y, cv = 5, scoring = "accuracy")

In [59]:
print(scores)

[0.7662 0.7721 0.7601 0.76   0.7621]